// DO NOT EDIT THIS FILE
// This file is automatically generated from the webgme-setup-tool.
'use strict';


var config = require('webgme/config/config.default'),
    validateConfig = require('webgme/config/validator');

// The paths can be loaded from the webgme-setup.json
config.plugin.basePaths.push(__dirname + '/../src/plugins');



config.visualization.panelPaths.push(__dirname + '/../src/visualizers/panels');


config.rest.components['routers/ConstraintResults'] = __dirname + '/../src/routers/ConstraintResults/ConstraintResults.js';

// Add requirejs paths
config.requirejsPaths = {
  'panels': './src/visualizers/panels',
  'widgets': './src/visualizers/widgets'
};


config.mongo.uri = 'mongodb://127.0.0.1:27017/webgme_constraint_checker';
validateConfig(config);
module.exports = config;
