/*globals define*/
/*jshint node:true*/

/**
 * Generated by RestRouterGenerator 2.2.0 from webgme on Thu Jan 12 2017 18:11:05 GMT-0600 (Central Standard Time).
 * To use in webgme add to gmeConfig.rest.components[<routePath>] = filePath.
 *
 * If you put this file in the root of your directory the following config,
 * gmeConfig.rest.component['path/subPath'] = path.join(process.cwd(), './ConstraintResults')
 * will expose, e.g. GET <host>/path/subPath/getExample, when running the server.
 */

'use strict';

// http://expressjs.com/en/guide/routing.html
var express = require('express'),
    superagent = require('superagent'),
    router = express.Router(),
    path = require('path'),
    STORAGE_CONSTANTS = requireJS('common/storage/constants'),
    componentJson = require(path.join(process.cwd(), 'config', 'components.json')),
    // Allow settings on global for tests.
    hookConfig = global.constraintCheckerHookConfig || componentJson.ConstraintCheckerHook ||
        require(path.join('..', '..', '..', 'config', 'components.json')).ConstraintCheckerHook,
    HOOK_BASE_URL = hookConfig.origin + ':' + hookConfig.port + '/' + hookConfig.id;

// FIXME: Check authorization on each request!

/**
 * Called when the server is created but before it starts to listening to incoming requests.
 * N.B. gmeAuth, safeStorage and workerManager are not ready to use until the start function is called.
 * (However inside an incoming request they are all ensured to have been initialized.)
 *
 * @param {object} middlewareOpts - Passed by the webgme server.
 * @param {GmeConfig} middlewareOpts.gmeConfig - GME config parameters.
 * @param {GmeLogger} middlewareOpts.logger - logger
 * @param {function} middlewareOpts.ensureAuthenticated - Ensures the user is authenticated.
 * @param {function} middlewareOpts.getUserId - If authenticated retrieves the userId from the request.
 * @param {object} middlewareOpts.gmeAuth - Authorization module.
 * @param {object} middlewareOpts.safeStorage - Accesses the storage and emits events (PROJECT_CREATED, COMMIT..).
 * @param {object} middlewareOpts.workerManager - Spawns and keeps track of "worker" sub-processes.
 */
function initialize(middlewareOpts) {
    var logger = middlewareOpts.logger.fork('ConstraintResults'),
        ensureAuthenticated = middlewareOpts.ensureAuthenticated,
        getUserId = middlewareOpts.getUserId,
        gmeAuth = middlewareOpts.gmeAuth,
        storage = middlewareOpts.safeStorage;

    logger.debug('initializing ...');

    // Ensure authenticated can be used only after this rule.
    router.use('*', ensureAuthenticated, function (req, res, next) {
        // TODO: set all headers, check rate limit, etc.

        // This header ensures that any failures with authentication won't redirect.
        res.setHeader('X-WebGME-Media-Type', 'webgme.v1');
        next();
    });

    router.get('/webhookStatus', function (req, res, next) {
        var hookUrl = [
            HOOK_BASE_URL,
            'status'
        ].join('/');

        superagent.get(hookUrl).end(function (err, data) {
            if (err) {
                res.json({error: 'No response from webhook!', errMessage: err.message});
            } else {
                res.json(data.body);
            }
        });
    });

    router.get('/:ownerId/:projectName/:type/:commitHash', function (req, res, next) {
        var hookUrl = [
            HOOK_BASE_URL,
            req.params.ownerId,
            req.params.projectName,
            req.params.type, // status or result
            req.params.commitHash
        ].join('/');

        superagent.get(hookUrl).end(function (err, data) {
            if (err) {
                next(err);
            } else {
                res.json(data.body);
            }
        });
    });

    if (hookConfig.addAtProjectCreation === true) {
        logger.info('Will add Constraint Checker Hook to new projects');
        storage.addEventListener(STORAGE_CONSTANTS.PROJECT_CREATED, function (_storage, data) {
            gmeAuth.metadataStorage.getProject(data.projectId)
                .then(function (projectData) {
                    var now = (new Date()).toISOString(),
                        hooks = projectData.hooks || {};

                    hooks[hookConfig.id] = {
                        url: HOOK_BASE_URL,
                        description: hookConfig.description,
                        events: hookConfig.events,
                        active: hookConfig.activeAtProjectCreation,
                        createdAt: now,
                        updatedAt: now
                    };

                    return gmeAuth.metadataStorage.updateProjectHooks(data.projectId, hooks);
                })
                .catch(function (err) {
                    logger.error('Failed to add constrain checker hook at project creation', err);
                });
        });
    }
}

/**
 * Called before the server starts listening.
 * @param {function} callback
 */
function start(callback) {
    callback();
}

/**
 * Called after the server stopped listening.
 * @param {function} callback
 */
function stop(callback) {
    callback();
}


module.exports = {
    initialize: initialize,
    router: router,
    start: start,
    stop: stop
};
